eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:8010/eureka/,http://localhost:8010/eureka/
logging:
    file: /var/log/todo.log
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
management:
    security:
        enabled: 'false '
server:
    port: 8017
spring:
    application:
        name: oauth
    boot:
        admin:
            url: http://admin:8026,http://localhost:8026
    jpa:
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                type: 'trace '
                use_sql_comments: true
